#!/usr/bin/env ruby

puts "Starting recording"

require_relative "./create_recording"
require "trollop"

options = Trollop::options do
  opt :file, "File name",  short: 'f', type: String
end

trap("SIGINT") {
  raise
}

start_time = Time.now
create_recording(file_name: options[:file]) do
  loop do
    begin
      current_time = (Time.now - start_time) * 1000
      content = current_time

      system *%W[tmux capture-pane]
      IO.popen(%W[tmux show-buffer]) do |out|
        create_frame(time: current_time, content: out.read)
      end
      sleep(0.1)
    rescue Exception => e
      break
    end
  end
end

puts "Recorded to: #{options[:file]}"
