#!/usr/bin/env ruby

require_relative "./create_recording"
#require "trollop"
#
#options = Trollop::options do
#  opt :file,       "File name",  short: 'f', type: String
#  opt :inputfile, "Input File", short: 'i', type: String
#  opt :timesfile, "Times File", short: 't', type: String
#end


Timing = Struct.new(:time, :chars)

timings = [].concat(File.open(ARGV[2]).each_line.map { |l|
  ll = l.split(" ")
  Timing.new(ll[0].to_f, ll[1].to_i)
}.sort_by{|t|t.time}
)

@start = 0
@end = 0
file = File.open(ARGV[1]) do |f|
  timings.each do |time|
    time.chars.times do
      print f.getc
    end
    sleep (time.time)
  end
end

#[46, 33].each do |t|
#    t.times do
#    print file.gets
#  end
#end
#frames = []
#
#create_recording(file_name: ARGV[0]) do
#  frames.each_with_index do |frame, i|
#    create_frame time: i*step, content: frame
#  end
#end

puts "Recorded to: #{ARGV[0]}"
