* T-Recs

[[https://travis-ci.org/iachettifederico/trecs][Build State]] [[https://travis-ci.org/iachettifederico/trecs.svg]]

#+BEGIN_EXAMPLE
                __________
               /  o       \
               |      ____|
               |     |___
               |    ____/
              _|   |
            _|     |===E
   /\     _|       ===E
   \ \___|         |
    \___          /
 _____ ____     _/
|_   _|  _ \ ___  ___ ___
  | | | |_) / _ \/ __/ __|
  | | |  _ <  __/ (__\__ \
  |_| |_| \_\___|\___|___/

#+END_EXAMPLE
Record screencasts in plain text.

** Installing TRecs
To install TRecs, just run
#+BEGIN_SRC bash
gem install trecs
#+END_SRC

** Usage
*** Reproduce a TRecs
You have a TRecs file and want to reproduce it? You can do it on a terminal using the =trecs= command.

Like this:
#+BEGIN_SRC bash
trecs <file>
#+END_SRC

You can also specify the refresh interval for the screen (terminal), using the =--step= argument.
The value has to be an integer representing the amount of milliseconds between each screen refresh.

#+BEGIN_SRC bash
trecs <file> --step=800
trecs <file> -s 800
#+END_SRC

*** Recording a TRecs
Wanna record a TRecs? Do it using the =trecs_record= command.

There are several recording plugins available for use

Each options has a set of available flags (NOTE: the =--help= argument don't explain each one in detail yet)

The main option to select the recording alternative is the Recording Strategy, passed to TRecs via the =--strategy= (=-s=) argument.

Here it's also available the =--step= option, which will define the time between frames in milliseconds.

**** Terminal session
The most obvious use for this gem is recording a terminal session. This feature will be the default in the future, but it's not fully implemented yet.

To record a terminal session, use the =--strategy=ttyrec= option:
#+BEGIN_SRC bash
trecs_record playing_with_bash.trecs --strategy=ttyrec
#+END_SRC

This will open a new terminal session to record. You can finish the recording typing =exit= or pressing =C-d=, then the session will be saved to =playing_with_bash.trecs= and will be ready for replaying.

**** Record a file's changes
You can record the changes that occur on a file by using =--strategy=raw-file=.

What this does is sample a file every =step= milliseconds and create a frame with that file's contents.

To use it:
#+BEGIN_SRC bash
trecs_record my_changes.trecs --strategy=raw_file
#+END_SRC

**** Incremental message TRecs
Another possibility is to record a text message that will appear on screen character by character with an interval of =step= milliseconds. This is currently the default functionality of the command =trecs_record=

#+BEGIN_SRC bash
trecs_record my_banner.trecs --strategy=incremental --step=50 --message="TRecs"
#+END_SRC

This will create 6 frames:

- 0 millis :: ""
- 50 millis :: "T"
- 100 millis :: "TR"
- 150 millis :: "TRe"
- 200 millis :: "TRec"
- 250 millis :: "TRecs"

**** Fly from right
Insert a message and se it fly from the right side of the screen

#+BEGIN_SRC bash
trecs_record my_banner.trecs --strategy=fly_from_right --step=50 --message="TRecs"
#+END_SRC

**** Shell command for message
On some recording strategies, there's also the posibility to run a custom shell command for each frame.

For example, you can use the =wc= shell command to count the characters (or lines or words) of a banner that, for example appears one char at the time

#+BEGIN_SRC bash
trecs_record my_banner.trecs --strategy=incremental --step=50 --message="TRecs" --command="echo <frame> | wc -c"
#+END_SRC

This will run, for each frame the command =<frame> | wc -c=

Where =<frame>= will be eplaced by the frame contents inside double quotes

And these are the generated frames with its corresponding commands:

- 0 millis ::
  - frame ::
    #+BEGIN_SRC bash
    0
    #+END_SRC
  - command ::
    #+BEGIN_EXAMPLE
    echo "" | wc -c
    #+END_EXAMPLE
- 50 millis ::
  - frame ::
    #+BEGIN_SRC bash
    1
    #+END_SRC
  - command ::
    #+BEGIN_EXAMPLE
    echo "T" | wc -c
    #+END_EXAMPLE
- 100 millis ::
  - frame ::
    #+BEGIN_SRC bash
    2
    #+END_SRC
  - command ::
    #+BEGIN_EXAMPLE
    echo "TR" | wc -c
    #+END_EXAMPLE
- 150 millis ::
  - frame ::
    #+BEGIN_SRC bash
    3
    #+END_SRC
  - command ::
    #+BEGIN_EXAMPLE
    echo "TRe" | wc -c
    #+END_EXAMPLE
- 200 millis ::
  - frame ::
    #+BEGIN_SRC bash
    4
    #+END_SRC
  - command ::
    #+BEGIN_EXAMPLE
    echo "TRec" | wc -c
    #+END_EXAMPLE
- 250 millis ::
  - frame ::
    #+BEGIN_SRC bash
    5
    #+END_SRC
  - command ::
    #+BEGIN_EXAMPLE
    echo "TRecs" | wc -c
    #+END_EXAMPLE

Currently applies to:
- Incremental Strategy
- Fly from right Strategy

** Extending TRecs
Right now, you can extend TRecs in three possible ways

- Recording Strategies :: This is the object that defines what to record and how to process the input to be converted into frames. To give an example, the IncrementalStrategy (provided by TRecs), will take an input string, make an array with each of it's characters and, for each char, append it to an output string and save the frame.
- Formats :: The format corresponds to the way the frames are stored. For example, using YamlStore, a tar file or a database.
- Tickers :: The Ticker is the way the user tells TRecs to advance frames.

# *** TODO Recording Strategies
# *** TODO Formats
# *** TODO Tickers
